// Database esercizi di base: [nome, gruppo, attrezzo]
const ESERCIZI_BASE = [
  // Petto
  ["Panca piana bilanciere", "Petto", "Bilanciere"],
  ["Panca piana manubri", "Petto", "Manubri"],
  ["Panca inclinata bilanciere", "Petto", "Bilanciere"],
  ["Panca inclinata manubri", "Petto", "Manubri"],
  ["Panca declinata", "Petto", "Bilanciere"],
  ["Croci con manubri", "Petto", "Manubri"],
  ["Croci ai cavi", "Petto", "Cavi"],
  ["Chest press", "Petto", "Macchinario"],
  ["Pectoral machine (pec deck)", "Petto", "Macchinario"],
  ["Piegamenti sulle braccia", "Petto", "Corpo libero"],
  ["Piegamenti inclinati (mani rialzate)", "Petto", "Corpo libero"],
  ["Dip alle parallele", "Petto", "Corpo libero"],
  // Schiena
  ["Trazioni alla sbarra", "Schiena", "Corpo libero"],
  ["Trazioni presa inversa", "Schiena", "Corpo libero"],
  ["Lat machine presa larga", "Schiena", "Cavi"],
  ["Lat machine presa stretta", "Schiena", "Cavi"],
  ["Pulley (low row)", "Schiena", "Cavi"],
  ["Rematore bilanciere", "Schiena", "Bilanciere"],
  ["Rematore manubrio", "Schiena", "Manubri"],
  ["Rematore al multipower", "Schiena", "Macchinario"],
  ["Row machine", "Schiena", "Macchinario"],
  ["Pulldown braccia tese", "Schiena", "Cavi"],
  ["Stacco da terra", "Schiena", "Bilanciere"],
  ["Iperestensioni", "Schiena", "Corpo libero"],
  ["Superman", "Schiena", "Corpo libero"],
  // Spalle
  ["Lento avanti bilanciere", "Spalle", "Bilanciere"],
  ["Lento avanti manubri", "Spalle", "Manubri"],
  ["Shoulder press", "Spalle", "Macchinario"],
  ["Alzate laterali manubri", "Spalle", "Manubri"],
  ["Alzate laterali ai cavi", "Spalle", "Cavi"],
  ["Alzate frontali", "Spalle", "Manubri"],
  ["Alzate a 90° (deltoide posteriore)", "Spalle", "Manubri"],
  ["Reverse pec deck", "Spalle", "Macchinario"],
  ["Face pull", "Spalle", "Cavi"],
  ["Tirate al mento", "Spalle", "Bilanciere"],
  ["Scrollate (trapezio)", "Spalle", "Manubri"],
  ["Pike push-up", "Spalle", "Corpo libero"],
  // Bicipiti
  ["Curl bilanciere", "Bicipiti", "Bilanciere"],
  ["Curl manubri alternato", "Bicipiti", "Manubri"],
  ["Curl a martello", "Bicipiti", "Manubri"],
  ["Curl su panca inclinata", "Bicipiti", "Manubri"],
  ["Curl al cavo basso", "Bicipiti", "Cavi"],
  ["Curl alla panca Scott", "Bicipiti", "Macchinario"],
  ["Curl concentrato", "Bicipiti", "Manubri"],
  // Tricipiti
  ["French press", "Tricipiti", "Bilanciere"],
  ["Pushdown al cavo", "Tricipiti", "Cavi"],
  ["Pushdown con corda", "Tricipiti", "Cavi"],
  ["Estensioni sopra la testa manubrio", "Tricipiti", "Manubri"],
  ["Kickback", "Tricipiti", "Manubri"],
  ["Panca presa stretta", "Tricipiti", "Bilanciere"],
  ["Dip alla panca", "Tricipiti", "Corpo libero"],
  ["Piegamenti a diamante", "Tricipiti", "Corpo libero"],
  // Gambe
  ["Squat bilanciere", "Gambe", "Bilanciere"],
  ["Squat al multipower", "Gambe", "Macchinario"],
  ["Front squat", "Gambe", "Bilanciere"],
  ["Goblet squat", "Gambe", "Manubri"],
  ["Leg press", "Gambe", "Macchinario"],
  ["Hack squat", "Gambe", "Macchinario"],
  ["Leg extension", "Gambe", "Macchinario"],
  ["Leg curl seduto", "Gambe", "Macchinario"],
  ["Leg curl sdraiato", "Gambe", "Macchinario"],
  ["Affondi con manubri", "Gambe", "Manubri"],
  ["Affondi camminati", "Gambe", "Corpo libero"],
  ["Affondi bulgari", "Gambe", "Manubri"],
  ["Stacco rumeno", "Gambe", "Bilanciere"],
  ["Hip thrust", "Gambe", "Bilanciere"],
  ["Ponte glutei", "Gambe", "Corpo libero"],
  ["Abduttori", "Gambe", "Macchinario"],
  ["Adduttori", "Gambe", "Macchinario"],
  ["Glute kickback ai cavi", "Gambe", "Cavi"],
  ["Calf in piedi", "Gambe", "Macchinario"],
  ["Calf seduto", "Gambe", "Macchinario"],
  ["Squat a corpo libero", "Gambe", "Corpo libero"],
  ["Step-up", "Gambe", "Corpo libero"],
  ["Wall sit (isometrico)", "Gambe", "Corpo libero"],
  ["Salti sul box", "Gambe", "Corpo libero"],
  // Addome
  ["Crunch", "Addome", "Corpo libero"],
  ["Crunch inverso", "Addome", "Corpo libero"],
  ["Crunch ai cavi", "Addome", "Cavi"],
  ["Sit-up", "Addome", "Corpo libero"],
  ["Plank", "Addome", "Corpo libero"],
  ["Plank laterale", "Addome", "Corpo libero"],
  ["Russian twist", "Addome", "Corpo libero"],
  ["Sollevamento gambe a terra", "Addome", "Corpo libero"],
  ["Sollevamento gambe alla sbarra", "Addome", "Corpo libero"],
  ["Mountain climber", "Addome", "Corpo libero"],
  ["Bicicletta (crunch)", "Addome", "Corpo libero"],
  ["Ab wheel", "Addome", "Attrezzo"],
  ["Bird dog", "Addome", "Corpo libero"],
  // Cardio / total body
  ["Tapis roulant", "Cardio", "Macchinario"],
  ["Cyclette", "Cardio", "Macchinario"],
  ["Ellittica", "Cardio", "Macchinario"],
  ["Vogatore", "Cardio", "Macchinario"],
  ["Corda per saltare", "Cardio", "Attrezzo"],
  ["Burpees", "Cardio", "Corpo libero"],
  ["Jumping jack", "Cardio", "Corpo libero"],
  ["Kettlebell swing", "Cardio", "Attrezzo"],
  // Mobilità
  ["Stretching", "Mobilità", "Corpo libero"],
  ["Mobilità spalle", "Mobilità", "Corpo libero"],
  ["Mobilità anche", "Mobilità", "Corpo libero"],
];
const GRUPPI = ["Petto", "Schiena", "Spalle", "Bicipiti", "Tricipiti", "Gambe", "Addome", "Cardio", "Mobilità", "Personalizzati"];
